# Import  libraries

In [253]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from datetime import timedelta

In [254]:
def Dataloader(CsvFile, ChunkSize, ChunkOverlap, OperationList):
#CsvFile = put in the filename(as string) example : matrix_player_15_game_2_quartersplit.csv
#ChunkSize = put in the size you want the chunks to be (in seconds) example: 1
#ChunkOverlap = the size you want the chunks to overlap (in seconds) example: 0.5
#Operationlist = input dataframe of names with operations that u want to make changes to. example:
                                #Operationlist = pd.DataFrame({'frAcc':['cal.mean'], 'wheelRotationalSpeedX':['cal.mea']})


#load in csv file
    df = pd.read_csv(CsvFile)

    chunks = [df[i:i+ChunkSize] for i in range(0,df.shape[0],ChunkOverlap)]

    frames = []

    for chunk in chunks:
        chunk = chunk.drop(columns=['Unnamed: 0'])
        frames.append(chunk)

        
    df_end =[]
    
    for frame in frames:
        if len(frame) == 100:
            result = [] #Reset the result array
            for column in list(frame.columns):
        
                if column in OperationList: #Check if column is in namelist
            
                    if OperationList[str(column)].values == 'cal.mean': #You can at more function if you want
                        X = cal.mean(frame[str(column)].tolist()) #Calculate mean of all columns named in namelist with operation cal.mean
            
                    else: #If the given operations isn't cal.mean
                        frame[str(column)] = [abs(ele) for ele in frame[str(column)]] #Get absolute value of all elements in list
                        X = max(frame[str(column)].tolist()) #Get single max value from list 
       
                else:
                    frame[str(column)] = [abs(ele) for ele in frame[str(column)]] #Get absolute value of all elements in list
                    X = max(frame[str(column)].tolist()) #Get single max value from list
            
                result.append(X) #Append results to list
        
            df_end.append(result) #Append all results into one big list
    
    df_end = pd.DataFrame(df_end, columns = list(frame.columns)) #Convert list to df
    return(df_end)

In [255]:
OperationList = [{ 'wheelRotationalSpeedX' : ['Cal.mean']}]
df_qs = pd.read_csv('Player_15_Game2_Sprints_Q12_V2-Copy1.csv')
df_qs

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,frAcc,frRoAcc,frDispl,frRoAng,...,frameRotationalSpeedY,frameRotationalSpeedZ,wheelRotationalSpeedX,wheelRotationalSpeedY,wheelRotationalSpeedZ,frRoSpeed,Filt_WheelX,Filt_FrameZ,Action,Quarter
0,0,0,0,0,0,0,19.69000,2828.9,3410.8,228.56000,...,19.7400,228.7000,84.7310,193.7800,108.4800,2456.100,67.674366,204.464236,0.0,1
1,1,1,1,1,1,1,22.80600,2828.8,3391.0,228.56000,...,19.7400,228.7000,113.6100,193.7800,108.4800,2456.100,77.254375,204.540434,0.0,1
2,2,2,2,2,2,2,22.80600,2828.5,3313.6,106.98000,...,8.3300,107.7900,159.6700,92.5400,55.6290,1530.100,112.519339,204.540434,0.0,1
3,3,3,3,3,3,3,13.70100,2829.1,3280.3,86.24200,...,7.9100,85.2600,288.6700,73.2430,55.6290,1530.100,143.311081,60.639928,0.0,1
4,4,4,4,4,4,4,14.08900,2829.9,3289.0,89.03700,...,7.5200,87.8500,410.7800,88.9700,33.1100,1006.200,266.441224,60.511982,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9054,9054,9054,9054,9054,9054,9054,0.70001,6556.8,1948.5,6.78380,...,1.5867,7.3220,5.6544,6.6500,5.1800,54.922,4.586872,8.607160,0.0,4
9055,9055,9055,9055,9055,9055,9055,0.40442,6556.8,1948.4,6.78380,...,1.0920,5.8800,5.4600,4.1922,2.1000,65.299,4.392796,5.850487,0.0,4
9056,9056,9056,9056,9056,9056,9056,0.36332,6556.8,1946.9,6.16700,...,1.0422,5.2640,5.4600,4.1922,2.1467,65.299,4.418443,3.237448,0.0,4
9057,9057,9057,9057,9057,9057,9057,0.17616,6556.8,1946.7,0.74254,...,1.0422,1.3222,2.4500,2.1700,2.1467,21.614,4.418443,2.107930,0.0,4
9058,9058,9058,9058,9058,9058,9058,0.12284,6556.8,1946.6,0.37909,...,1.0360,1.2600,1.6660,1.5789,1.7500,13.551,2.188870,1.195376,0.0,4

In [256]:
df_RNN = pd.read_csv('Predictions_15x2_Quartor4_Overlap.csv')
df_RF = pd.read_csv('Sprint_results_randomforest_Q4.csv')

In [257]:
df_RNN = df_RNN.drop(columns=['Unnamed: 0'])
df_RF = df_RF.drop(columns=['Unnamed: 0'])

In [258]:
df = pd.concat([df_RF, df_RNN], axis=1)

In [259]:
df = df[['timeLine','Action','0']]

In [260]:
df = df.fillna(0)
df['0'] = df['0'].astype(int)
df['Action'] = df['Action'].astype(int)
df = df.rename(columns={'Action':'Action_RF', '0':'Action_RNN'})

In [261]:
df = df[(df['Action_RF'] == df['Action_RNN'])]
df = df[df['Action_RF'] == 1]

In [262]:
df

     timeLine  Action_RF  Action_RNN
6      7673.0          1           1
7      7673.5          1           1
8      7674.0          1           1
9      7674.5          1           1
10     7675.0          1           1
..        ...        ...         ...
781    8060.5          1           1
782    8061.0          1           1
783    8061.5          1           1
785    8062.5          1           1
791    8065.5          1           1

[224 rows x 3 columns]

In [263]:
df_check = df

In [264]:
#df_qs = df_qs.drop(columns=['Unnamed: 0'])
print(df_qs.loc[df_qs.timeLine == 7673])

      Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
7196        7196          7196            7196              7196

      Unnamed: 0.1.1.1.1  Unnamed: 0.1.1.1.1.1   frAcc  frRoAcc  frDispl  \
7196                7196                  7196  12.459   6051.1   544.82

      frRoAng  ...  frameRotationalSpeedY  frameRotationalSpeedZ  \
7196    39.73  ...                  6.636                  40.32

      wheelRotationalSpeedX  wheelRotationalSpeedY  wheelRotationalSpeedZ  \
7196                 441.81                 42.266                 34.832

      frRoSpeed  Filt_WheelX  Filt_FrameZ  Action  Quarter
7196     984.78   382.094876    31.595684     0.0        4

[1 rows x 23 columns]

In [265]:
Check = df_check.timeLine.to_numpy()

In [266]:
Check

array([7673. , 7673.5, 7674. , 7674.5, 7675. , 7688.5, 7689. , 7689.5,
       7690. , 7690.5, 7693. , 7693.5, 7694. , 7694.5, 7695. , 7697. ,
       7697.5, 7698. , 7715.5, 7724.5, 7725. , 7730. , 7730.5, 7731. ,
       7731.5, 7732. , 7732.5, 7767. , 7767.5, 7768. , 7768.5, 7769. ,
       7769.5, 7770. , 7770.5, 7772.5, 7773. , 7773.5, 7774. , 7776.5,
       7777. , 7783. , 7783.5, 7784. , 7784.5, 7785. , 7785.5, 7786. ,
       7786.5, 7787. , 7787.5, 7788. , 7793.5, 7794. , 7804. , 7804.5,
       7805. , 7805.5, 7806. , 7806.5, 7807. , 7807.5, 7808. , 7808.5,
       7809. , 7809.5, 7811.5, 7812. , 7812.5, 7813. , 7813.5, 7814. ,
       7814.5, 7815. , 7815.5, 7816. , 7816.5, 7818.5, 7819.5, 7820. ,
       7820.5, 7826. , 7827. , 7838.5, 7839. , 7839.5, 7840. , 7840.5,
       7841. , 7841.5, 7842. , 7842.5, 7843. , 7843.5, 7844. , 7844.5,
       7845. , 7845.5, 7846. , 7854.5, 7860. , 7867. , 7867.5, 7868. ,
       7900. , 7900.5, 7901. , 7901.5, 7902. , 7902.5, 7903. , 7903.5,
       7904. , 7904.5, 7905. , 7905.5, 7906. , 7906.5, 7908.5, 7922. ,
       7922.5, 7923. , 7925.5, 7926. , 7926.5, 7927. , 7927.5, 7928. ,
       7928.5, 7929. , 7929.5, 7930. , 7930.5, 7931. , 7931.5, 7932. ,
       7932.5, 7946.5, 7947. , 7947.5, 7948. , 7948.5, 7949. , 7949.5,
       7950. , 7950.5, 7951. , 7951.5, 7952. , 7952.5, 7953. , 7953.5,
       7954. , 7954.5, 7975. , 7975.5, 7976. , 7976.5, 7977. , 7977.5,
       7978. , 7978.5, 7979. , 7979.5, 7980. , 7980.5, 7981. , 7981.5,
       7986. , 7986.5, 7987. , 7987.5, 7988. , 7988.5, 7989. , 7989.5,
       7990. , 7990.5, 7991. , 7991.5, 7992. , 7992.5, 7993. , 8011. ,
       8011.5, 8012. , 8012.5, 8013. , 8013.5, 8014. , 8014.5, 8015. ,
       8015.5, 8016. , 8016.5, 8017. , 8017.5, 8018. , 8023. , 8023.5,
       8024. , 8024.5, 8038. , 8038.5, 8039. , 8039.5, 8040. , 8040.5,
       8041. , 8041.5, 8042. , 8042.5, 8043. , 8043.5, 8045.5, 8046. ,
       8047. , 8059.5, 8060. , 8060.5, 8061. , 8061.5, 8062.5, 8065.5])

In [267]:
for time in Check:
    df_qs.loc[df_qs['timeLine'] == time, 'Action'] = 1

In [268]:
print(df_qs.loc[df_qs.timeLine == 4911])

      Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  \
2658        2658          2658            2658              2658

      Unnamed: 0.1.1.1.1  Unnamed: 0.1.1.1.1.1   frAcc  frRoAcc  frDispl  \
2658                2658                  2658  8.7405   3729.9   3138.4

      frRoAng  ...  frameRotationalSpeedY  frameRotationalSpeedZ  \
2658   134.11  ...                 10.892                 132.75

      wheelRotationalSpeedX  wheelRotationalSpeedY  wheelRotationalSpeedZ  \
2658                 397.17                 130.91                 56.742

      frRoSpeed  Filt_WheelX  Filt_FrameZ  Action  Quarter
2658     907.86   348.561735   107.129099     1.0        2

[1 rows x 23 columns]

In [269]:
df_qs

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,frAcc,frRoAcc,frDispl,frRoAng,...,frameRotationalSpeedY,frameRotationalSpeedZ,wheelRotationalSpeedX,wheelRotationalSpeedY,wheelRotationalSpeedZ,frRoSpeed,Filt_WheelX,Filt_FrameZ,Action,Quarter
0,0,0,0,0,0,0,19.69000,2828.9,3410.8,228.56000,...,19.7400,228.7000,84.7310,193.7800,108.4800,2456.100,67.674366,204.464236,0.0,1
1,1,1,1,1,1,1,22.80600,2828.8,3391.0,228.56000,...,19.7400,228.7000,113.6100,193.7800,108.4800,2456.100,77.254375,204.540434,0.0,1
2,2,2,2,2,2,2,22.80600,2828.5,3313.6,106.98000,...,8.3300,107.7900,159.6700,92.5400,55.6290,1530.100,112.519339,204.540434,0.0,1
3,3,3,3,3,3,3,13.70100,2829.1,3280.3,86.24200,...,7.9100,85.2600,288.6700,73.2430,55.6290,1530.100,143.311081,60.639928,0.0,1
4,4,4,4,4,4,4,14.08900,2829.9,3289.0,89.03700,...,7.5200,87.8500,410.7800,88.9700,33.1100,1006.200,266.441224,60.511982,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9054,9054,9054,9054,9054,9054,9054,0.70001,6556.8,1948.5,6.78380,...,1.5867,7.3220,5.6544,6.6500,5.1800,54.922,4.586872,8.607160,0.0,4
9055,9055,9055,9055,9055,9055,9055,0.40442,6556.8,1948.4,6.78380,...,1.0920,5.8800,5.4600,4.1922,2.1000,65.299,4.392796,5.850487,0.0,4
9056,9056,9056,9056,9056,9056,9056,0.36332,6556.8,1946.9,6.16700,...,1.0422,5.2640,5.4600,4.1922,2.1467,65.299,4.418443,3.237448,0.0,4
9057,9057,9057,9057,9057,9057,9057,0.17616,6556.8,1946.7,0.74254,...,1.0422,1.3222,2.4500,2.1700,2.1467,21.614,4.418443,2.107930,0.0,4
9058,9058,9058,9058,9058,9058,9058,0.12284,6556.8,1946.6,0.37909,...,1.0360,1.2600,1.6660,1.5789,1.7500,13.551,2.188870,1.195376,0.0,4

In [270]:
df_qs.to_csv('Player_15_Game2_Sprints_Q124_V2.csv')